### ISSUE TITLE
Build process for Linux

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder-desktop#13]
Currently, releases are listed in snap format for Linux, but changing the URL manually to end on AppImage reveals the AppImage, too.

![image](https://user-images.githubusercontent.com/571494/57029532-5454dd80-6c42-11e9-93ee-403ace76b26b.png)

See https://github.com/webrecorder/webrecorder-desktop/releases/download/untagged-4584f4f1591752a50b6f/webrecorder-1.7.0.AppImage

AppImage is a very practical format and should definitely be listed.

**Comment by ikreymer** [comment]
AppImage now also being built
