### ISSUE TITLE
There's been an error: No such page or content is not accessible.

### ISSUE THREAD

**Issue by holdit** [webrecorder/webrecorder-desktop#22]
I downloaded the available .dng file (v2.0.0) for Mac (macOS 10.14.6) and I get it to work. I get this error message:

<img width="1020" alt="Screenshot 2019-09-26 at 18 18 53" src="https://user-images.githubusercontent.com/23439751/65710161-58b6e280-e08a-11e9-96bb-3e23a0d1bdfb.png">

Both links inside the "user" icon (top right) don't do anything. All that works inside this window is the "help" link that sends me to this repo.

Any suggestions to fix this? Thanks in advance.

**Comment by ikreymer** [comment]
It looks like your system username is `c`, and Desktop app automatically creates a user account using the system username. However, it requires usernames to be at least 4 characters long, so this is likely an issue.

To confirm that this is the issue, are you able to test Webrecorder Desktop on another account that has a different, longer username?

We'll look at a way to address this if this is the issue!

**Comment by holdit** [comment]
It works with a bigger username:

<img width="1112" alt="Screenshot 2019-10-05 at 18 24 20" src="https://user-images.githubusercontent.com/23439751/66258648-abd21900-e79f-11e9-8edc-e45da2237ef2.png">
