### ISSUE TITLE
How to change the Data Directory

### ISSUE THREAD

**Issue by peter1000** [webrecorder/webrecorder-desktop#33]
Hi,
Thanks for sharing your app. I have a questions is it possible to change/configure the *Data Directory*: `/home/USERNAME/Documents/Webrecorder-Data`

Thanks a lot

**Comment by m4rk3r** [comment]
Unfortunately right now it's not that easily configurable. If you're willing to [build from source](https://github.com/webrecorder/webrecorder-desktop#building-webrecorder-desktop), you can modify the data directory [here](https://github.com/webrecorder/webrecorder-desktop/blob/master/app/main.js#L28)
