### ISSUE TITLE
Web Recorder/Redis doesn't load its configuration correctly in Windows 10 when username has a space in its name.

### ISSUE THREAD

**Issue by ghost** [webrecorder/webrecorder-desktop#35]
My windows username has a space in its name; this causes an error with Redis' generated configuration file, and I can't attempt to fix the config file, by, for example, adding quotes around the path, because Web Recorder keeps reverting the file on launch. No windows open except a very fast black console/terminal that closes as soon as it loads.

**Comment by dumdam** [comment]
Download and install first file of this list - https://github.com/rgl/redis/downloads

Then try to run webrecorder. (This works for me)

If still have the problem,

1. Try clearing the temp files (manually or using a cleanup programme) for previous installations.

2. Stop the redis service from Task manager -> Services -> redis (Stop this)

Then try again.

Hope this helpful :)

**Comment by m4rk3r** [comment]
This is fixed in https://github.com/webrecorder/webrecorder-desktop/releases/tag/v2.0.1
