### ISSUE TITLE
Offline usage not possible under Windows

### ISSUE THREAD

**Issue by int3l** [webrecorder/webrecorder-desktop#39]
Hi, I am trying to view a WARC file/collection in offline mode (without internet access).
It seems that this doesn't work neither in WebRecorder Desktop 2.0.1 or Player 1.8.0 for Windows 10.

Is there anything that I am missing?
On the home page of webrecorder.io it literally says:
```
Webrecorder Player App
Use this desktop web archive viewer to browse exported collections, even when you are offline.
```

I am not doing anything specific:
1. Just downloading the windows release.
2. Opening and capturing a session.
3. Restart the app without with internet disabled.
4. The result is that the the sessions/pages doesn't load in the **Browsing** mode.

Is this option only available in webrecorder.io?

PS: I even created account on webrecorder.io and exported WARC collection from there in order to double check.

**Comment by int3l** [comment]
I am trying this exact steps as shown in this YT video: [Web Archiving for All with Webrecorder.io](https://youtu.be/2aXlmjz92YQ?t=2443)

**Comment by vezycash** [comment]
@int3l offline usage works for me. 

For whatever reason, Webrecorder first downloads something from the aws on startup - a certificate maybe. It's less than 100KB. After that, you can go offline and everything will work until you restart the app.
