### ISSUE TITLE
Minimum UI changes page for desktop app beta

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder-desktop#5]
Related to #4, what are the minimum UI changes needed for desktop app to be beta tested, besides user settings, to make it more clear its a desktop app?
Mostly everything works, but perhaps more distinction is needed (eg. no need to set collections to public?)

**Comment by despens** [comment]
- remove footer
- remove menu bar features that don't work, leave in File→Open ^O, File→Quit ^Q, and toggling dev tools via View. 
- user menu    
  - remove "signed in as"
  - remove "space used"
  - remove "account settings"
- mark outside links with some symbol?
- change some wording:
  - upload to import
  - download to export
- Visual distinction bw Desktop App & Web
- top bar distinction  
- Think about logo for player vs app

**Comment by ikreymer** [comment]
All Done! (only outside link is Help for now!)
